name: Action Workflow

on:
  push:
    branches:
      - main

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $_GITHUB_REPOSITORY
          echo $_GITHUB_WORKSPACE
          echo "${github.token}"
        #   git clone git@github.com:bicosteve/githubactions
        #   git checkout $GITHUB_SHA
      - name: Checkout
        uses: actions/checkout@v1 #authenticate with your repository commit and pullcode
      - name: List Files After Checout
        run: |
          pwd
          ls -a
      - name: Simple Javascript Action
        id: greet
        # action-code someone has written and you can use in your code
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: John
      - name: Log Greeting Time
        # github actions stores variable of step ids
        run: echo "${{ steps.greet.outputs.time }}"
